name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal code or repo to reproduce the issue.
    validations:
      required: true
  - type: dropdown
    id: adapter
    attributes:
      label: Adapter
      options:
        - Hono
        - Express
        - Koa
        - Elysia
        - None / Core
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "0.0.1"
    validations:
      required: true
