// ⚠️ Auto-generated by routed. Do not edit.
import { defineRouteTree } from "routedjs";
import express from "express";
import { routeHandler, wrapMiddleware } from "routedjs/express";

import middleware_root from "./routes/_middleware.ts";
import middleware_users from "./routes/users/_middleware.ts";

import route_group_internal_metrics_get from "./routes/_internal/metrics.get.route.ts";
import route_health_get from "./routes/health.get.route.ts";
import route_users_param_userId_visits_param_visitId_get from "./routes/users/$userId/visits/$visitId.get.route.ts";
import route_users_param_userId_visits_get from "./routes/users/$userId/visits.get.route.ts";
import route_users_param_userId_delete from "./routes/users/$userId.delete.route.ts";
import route_users_param_userId_get from "./routes/users/$userId.get.route.ts";
import route_users_param_userId_put from "./routes/users/$userId.put.route.ts";
import route_users_index_get from "./routes/users/index.get.route.ts";
import route_users_index_post from "./routes/users/index.post.route.ts";
import route_me_index_get from "./routes/me/index.get.route.ts";

export const routeTree = defineRouteTree([
  {
    path: "/metrics",
    method: "get",
    route: route_group_internal_metrics_get,
    middleware: [middleware_root],
  },
  {
    path: "/health",
    method: "get",
    route: route_health_get,
    middleware: [middleware_root],
  },
  {
    path: "/users/:userId/visits/:visitId",
    method: "get",
    route: route_users_param_userId_visits_param_visitId_get,
    middleware: [middleware_root, middleware_users],
  },
  {
    path: "/users/:userId/visits",
    method: "get",
    route: route_users_param_userId_visits_get,
    middleware: [middleware_root, middleware_users],
  },
  {
    path: "/users/:userId",
    method: "delete",
    route: route_users_param_userId_delete,
    middleware: [middleware_root, middleware_users],
  },
  {
    path: "/users/:userId",
    method: "get",
    route: route_users_param_userId_get,
    middleware: [middleware_root, middleware_users],
  },
  {
    path: "/users/:userId",
    method: "put",
    route: route_users_param_userId_put,
    middleware: [middleware_root, middleware_users],
  },
  {
    path: "/users",
    method: "get",
    route: route_users_index_get,
    middleware: [middleware_root, middleware_users],
  },
  {
    path: "/users",
    method: "post",
    route: route_users_index_post,
    middleware: [middleware_root, middleware_users],
  },
  {
    path: "/me",
    method: "get",
    route: route_me_index_get,
    middleware: [middleware_root],
  },
]);

export const app = express();

app.use("*", wrapMiddleware(middleware_root));
app.use("/users/*", wrapMiddleware(middleware_users));
app.get("/metrics", routeHandler(route_group_internal_metrics_get, "/metrics"));
app.get("/health", routeHandler(route_health_get, "/health"));
app.get("/users/:userId/visits/:visitId", routeHandler(route_users_param_userId_visits_param_visitId_get, "/users/:userId/visits/:visitId"));
app.get("/users/:userId/visits", routeHandler(route_users_param_userId_visits_get, "/users/:userId/visits"));
app.delete("/users/:userId", routeHandler(route_users_param_userId_delete, "/users/:userId"));
app.get("/users/:userId", routeHandler(route_users_param_userId_get, "/users/:userId"));
app.put("/users/:userId", routeHandler(route_users_param_userId_put, "/users/:userId"));
app.get("/users", routeHandler(route_users_index_get, "/users"));
app.post("/users", routeHandler(route_users_index_post, "/users"));
app.get("/me", routeHandler(route_me_index_get, "/me"));
