// ⚠️ Auto-generated by routed. Do not edit.
import express from "express";
import { routeHandler, wrapMiddleware } from "routedjs/express";

import middleware0 from "./routes/_middleware.ts";
import middleware1 from "./routes/users/_middleware.ts";

import route0 from "./routes/health.get.route.ts";
import route1 from "./routes/me/index.get.route.ts";
import route2 from "./routes/_internal/metrics.get.route.ts";
import route3 from "./routes/users/index.get.route.ts";
import route4 from "./routes/users/index.post.route.ts";
import route5 from "./routes/users/$userId.delete.route.ts";
import route6 from "./routes/users/$userId.get.route.ts";
import route7 from "./routes/users/$userId.put.route.ts";
import route8 from "./routes/users/$userId/visits.get.route.ts";
import route9 from "./routes/users/$userId/visits/$visitId.get.route.ts";

export const app = express();

app.use("*", wrapMiddleware(middleware0));
app.use("/users/*", wrapMiddleware(middleware1));
app.get("/health", routeHandler(route0, "/health"));
app.get("/me", routeHandler(route1, "/me"));
app.get("/metrics", routeHandler(route2, "/metrics"));
app.get("/users", routeHandler(route3, "/users"));
app.post("/users", routeHandler(route4, "/users"));
app.delete("/users/:userId", routeHandler(route5, "/users/:userId"));
app.get("/users/:userId", routeHandler(route6, "/users/:userId"));
app.put("/users/:userId", routeHandler(route7, "/users/:userId"));
app.get("/users/:userId/visits", routeHandler(route8, "/users/:userId/visits"));
app.get("/users/:userId/visits/:visitId", routeHandler(route9, "/users/:userId/visits/:visitId"));
