import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm, mkdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { generate } from "../generate.ts";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await mkdtemp(path.join(os.tmpdir(), "routed-e2e-"));
});

afterEach(async () => {
  await rm(tmpDir, { recursive: true, force: true });
});

/** Write a minimal route file that default-exports a createRoute call. */
async function writeRouteFile(dir: string, fileName: string): Promise<void> {
  const filePath = path.join(dir, fileName);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(
    filePath,
    `import { createRoute } from "routedjs";
export default createRoute({ handler: () => ({}) });
`,
  );
}

/** Write a minimal middleware file that default-exports a createMiddleware call. */
async function writeMiddlewareFile(dir: string): Promise<void> {
  const filePath = path.join(dir, "_middleware.ts");
  await mkdir(dir, { recursive: true });
  await writeFile(
    filePath,
    `import { createMiddleware } from "routedjs";
export default createMiddleware(async ({ next }) => { await next(); });
`,
  );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("generate (end-to-end)", () => {
  test("generates correct manifest for simple route structure", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "index.get.route.ts");
    await writeRouteFile(routesDir, "users/index.get.route.ts");
    await writeRouteFile(routesDir, "users/index.post.route.ts");

    const result = await generate({ routesDir, outFile });

    expect(result.routeCount).toBe(3);
    expect(result.middlewareCount).toBe(0);

    const content = await readFile(outFile, "utf-8");

    // Has auto-generated header
    expect(content).toContain("Auto-generated by routed");

    // Imports defineRouteTree
    expect(content).toContain('import { defineRouteTree } from "routedjs"');

    // Imports all three route files
    expect(content).toContain("import route_index_get");
    expect(content).toContain("import route_users_index_get");
    expect(content).toContain("import route_users_index_post");

    // Contains correct paths
    expect(content).toContain('path: "/"');
    expect(content).toContain('path: "/users"');

    // Contains correct methods
    expect(content).toContain('method: "get"');
    expect(content).toContain('method: "post"');

    // No middleware
    expect(content).toContain("middleware: []");
  });

  test("includes middleware imports and associates them with routes", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeMiddlewareFile(routesDir);
    await writeRouteFile(routesDir, "index.get.route.ts");
    await writeRouteFile(routesDir, "users/index.get.route.ts");

    const result = await generate({ routesDir, outFile });

    expect(result.routeCount).toBe(2);
    expect(result.middlewareCount).toBe(1);

    const content = await readFile(outFile, "utf-8");

    // Has middleware import
    expect(content).toContain("import middleware_root");
    expect(content).toContain("_middleware.ts");

    // Both routes get the root middleware
    expect(content).toContain("middleware: [middleware_root]");
    // No routes should have empty middleware since root middleware applies to all
    expect(content).not.toContain("middleware: []");
  });

  test("nested _middleware.ts applies to routes in that directory", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    // Root middleware
    await writeMiddlewareFile(routesDir);
    // Nested middleware
    await writeMiddlewareFile(path.join(routesDir, "users"));

    await writeRouteFile(routesDir, "index.get.route.ts");
    await writeRouteFile(routesDir, "users/index.get.route.ts");
    await writeRouteFile(routesDir, "users/$userId/index.get.route.ts");

    const result = await generate({ routesDir, outFile });

    expect(result.routeCount).toBe(3);
    expect(result.middlewareCount).toBe(2);

    const content = await readFile(outFile, "utf-8");

    // Both middleware imports exist
    expect(content).toContain("import middleware_root");
    expect(content).toContain("import middleware_users");

    // Parse the entries to check middleware association
    // Root route (/) gets only root middleware
    // Users routes get root + users middleware
    const lines = content.split("\n");

    // Find lines with path and the following middleware line
    const entries: { path: string; middleware: string }[] = [];
    for (let i = 0; i < lines.length; i++) {
      const pathMatch = lines[i]!.match(/path: "([^"]+)"/);
      if (pathMatch) {
        // middleware line is 2 lines after path (path, method, route, middleware)
        const mwLine = lines[i + 3];
        entries.push({ path: pathMatch[1]!, middleware: mwLine!.trim() });
      }
    }

    // Root route gets only root middleware
    const rootEntry = entries.find((e) => e.path === "/");
    expect(rootEntry).toBeDefined();
    expect(rootEntry!.middleware).toContain("middleware_root");
    expect(rootEntry!.middleware).not.toContain("middleware_users");

    // /users route gets both middlewares
    const usersEntry = entries.find(
      (e) => e.path === "/users",
    );
    expect(usersEntry).toBeDefined();
    expect(usersEntry!.middleware).toContain("middleware_root");
    expect(usersEntry!.middleware).toContain("middleware_users");

    // /users/:userId route also gets both middlewares
    const userIdEntry = entries.find((e) => e.path === "/users/:userId");
    expect(userIdEntry).toBeDefined();
    expect(userIdEntry!.middleware).toContain("middleware_root");
    expect(userIdEntry!.middleware).toContain("middleware_users");
  });

  test("empty routes directory produces empty route tree", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await mkdir(routesDir, { recursive: true });

    const result = await generate({ routesDir, outFile });

    expect(result.routeCount).toBe(0);
    expect(result.middlewareCount).toBe(0);

    const content = await readFile(outFile, "utf-8");

    expect(content).toContain("defineRouteTree([");
    expect(content).toContain("]);");
    // No route imports
    expect(content).not.toContain("import route");
    // No middleware imports
    expect(content).not.toContain("import middleware");
    // No route entries inside the array
    expect(content).not.toContain("path:");
    expect(content).not.toContain("method:");
  });

  test("route import names stay stable when a new route is inserted", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "health.get.route.ts");
    await writeRouteFile(routesDir, "users/$userId.get.route.ts");

    await generate({ routesDir, outFile });
    const before = await readFile(outFile, "utf-8");

    await writeRouteFile(routesDir, "users/activity.get.route.ts");
    await generate({ routesDir, outFile });
    const after = await readFile(outFile, "utf-8");

    const existingImports = [
      'import route_health_get from "./routes/health.get.route.ts";',
      'import route_users_param_userId_get from "./routes/users/$userId.get.route.ts";',
    ];

    for (const importLine of existingImports) {
      expect(before).toContain(importLine);
      expect(after).toContain(importLine);
    }

    expect(after).toContain(
      'import route_users_activity_get from "./routes/users/activity.get.route.ts";',
    );
    expect(after).not.toContain("import route0");
  });

  test("pathless groups (_prefix dirs) don't add to URL path", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "_admin/dashboard.get.route.ts");
    await writeRouteFile(routesDir, "_auth/login.post.route.ts");

    const result = await generate({ routesDir, outFile });

    expect(result.routeCount).toBe(2);

    const content = await readFile(outFile, "utf-8");

    // _admin and _auth are stripped from the URL path
    expect(content).toContain('path: "/dashboard"');
    expect(content).toContain('path: "/login"');

    // They should NOT appear in the URL path
    expect(content).not.toContain('path: "/_admin');
    expect(content).not.toContain('path: "/_auth');
  });

  test("index files map to directory root", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "index.get.route.ts");
    await writeRouteFile(routesDir, "users/index.get.route.ts");
    await writeRouteFile(routesDir, "users/$userId/index.get.route.ts");

    await generate({ routesDir, outFile });

    const content = await readFile(outFile, "utf-8");

    // index.get.route.ts at root maps to "/"
    expect(content).toContain('path: "/"');
    // users/index.get.route.ts maps to "/users", not "/users/index"
    expect(content).toContain('path: "/users"');
    // users/$userId/index.get.route.ts maps to "/users/:userId"
    expect(content).toContain('path: "/users/:userId"');

    // "index" should never appear in a path
    expect(content).not.toMatch(/path: "[^"]*index/);
  });

  test("dynamic params are converted from $ to : notation", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "users/$userId.get.route.ts");
    await writeRouteFile(
      routesDir,
      "orgs/$orgId/members/$memberId.get.route.ts",
    );

    await generate({ routesDir, outFile });

    const content = await readFile(outFile, "utf-8");

    expect(content).toContain('path: "/users/:userId"');
    expect(content).toContain('path: "/orgs/:orgId/members/:memberId"');

    // $ should not appear in any path
    expect(content).not.toMatch(/path: "[^"]*\$/);
  });

  test("catch-all params are converted from $$ to :name* notation", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "storage/$$path.get.route.ts");
    await writeRouteFile(routesDir, "storage/_internal/$$asset/index.get.route.ts");

    await generate({ routesDir, outFile });

    const content = await readFile(outFile, "utf-8");

    expect(content).toContain('path: "/storage/:path*"');
    expect(content).toContain('path: "/storage/:asset*"');
  });

  test("routes preserve method order within the same path after specificity sorting", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    // Create in non-sorted order
    await writeRouteFile(routesDir, "users/index.post.route.ts");
    await writeRouteFile(routesDir, "index.get.route.ts");
    await writeRouteFile(routesDir, "users/index.get.route.ts");

    await generate({ routesDir, outFile });

    const content = await readFile(outFile, "utf-8");

    // Find path lines in order
    const pathMatches = [...content.matchAll(/path: "([^"]+)"/g)].map(
      (m) => m[1],
    );

    // Same-path methods should stay stable after route specificity sorting.
    expect(pathMatches.filter((path) => path === "/users")).toHaveLength(2);

    // Find method lines in order for /users
    const lines = content.split("\n");
    const usersMethods: string[] = [];
    for (let i = 0; i < lines.length; i++) {
      if (lines[i]!.includes('path: "/users"')) {
        const methodLine = lines[i + 1]!;
        const methodMatch = methodLine.match(/method: "([^"]+)"/);
        if (methodMatch) usersMethods.push(methodMatch[1]!);
      }
    }

    // "get" should come before "post" for /users
    expect(usersMethods).toEqual(["get", "post"]);
  });

  test("static sibling routes are emitted before parameterized siblings", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "workspaces/$id.get.route.ts");
    await writeRouteFile(routesDir, "workspaces/activity.get.route.ts");
    await writeRouteFile(routesDir, "workspaces/$$path.get.route.ts");

    await generate({ routesDir, outFile });

    const content = await readFile(outFile, "utf-8");
    const pathMatches = [...content.matchAll(/path: "([^"]+)"/g)].map((m) => m[1]);

    expect(pathMatches).toEqual([
      "/workspaces/activity",
      "/workspaces/:id",
      "/workspaces/:path*",
    ]);
  });

  test("all HTTP methods are correctly extracted", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "manifest.ts");

    await writeRouteFile(routesDir, "index.get.route.ts");
    await writeRouteFile(routesDir, "index.post.route.ts");
    await writeRouteFile(routesDir, "index.put.route.ts");
    await writeRouteFile(routesDir, "index.patch.route.ts");
    await writeRouteFile(routesDir, "index.delete.route.ts");

    const result = await generate({ routesDir, outFile });

    expect(result.routeCount).toBe(5);

    const content = await readFile(outFile, "utf-8");

    expect(content).toContain('method: "get"');
    expect(content).toContain('method: "post"');
    expect(content).toContain('method: "put"');
    expect(content).toContain('method: "patch"');
    expect(content).toContain('method: "delete"');
  });

  test("generates a typed Hono app when framework is set", async () => {
    const routesDir = path.join(tmpDir, "routes");
    const outFile = path.join(tmpDir, "app.ts");

    await writeMiddlewareFile(routesDir);
    await writeMiddlewareFile(path.join(routesDir, "users", "admin"));
    await writeRouteFile(routesDir, "users/admin/$userId.get.route.ts");
    await writeRouteFile(routesDir, "storage/$$path.get.route.ts");

    await generate({
      routesDir,
      outFile,
      framework: "hono",
    });

    const content = await readFile(outFile, "utf-8");

    expect(content).toContain('import { defineRouteTree } from "routedjs"');
    expect(content).toContain('import { Hono } from "hono"');
    expect(content).toContain('import { routeHandler, wrapMiddleware } from "routedjs/hono"');
    expect(content).toContain("export const routeTree = defineRouteTree([");
    expect(content).toContain('.use("*", wrapMiddleware(middleware_root))');
    expect(content).toContain('.use("/users/admin/*", wrapMiddleware(middleware_users_admin))');
    expect(content).toContain(
      '.get("/storage/:path{.+}", routeHandler(route_storage_catchAll_path_get, "/storage/:path*"))',
    );
    expect(content).toContain(
      '.get("/users/admin/:userId", routeHandler(route_users_admin_param_userId_get, "/users/admin/:userId"))',
    );
    expect(content).toContain("export type AppType = typeof app;");
  });
});
