import path from "node:path";

export type CodegenRoute = {
  filePath: string;
  urlPath: string;
  method: string;
};

export type CodegenMiddleware = {
  filePath: string;
  directory: string;
};

export function resolveMiddlewareForRoute(
  routeRelativeDir: string,
  middlewares: CodegenMiddleware[],
): CodegenMiddleware[] {
  return middlewares.filter((mw) => {
    if (mw.directory === ".") return true;
    return (
      routeRelativeDir === mw.directory ||
      routeRelativeDir.startsWith(mw.directory + path.sep)
    );
  });
}

export function toRelativeImport(fromDir: string, toFile: string): string {
  let rel = path.relative(fromDir, toFile);
  if (!rel.startsWith(".")) {
    rel = "./" + rel;
  }
  return rel;
}

export function routeImportName(route: CodegenRoute, routesDir: string): string {
  return stableImportName("route", routesDir, route.filePath);
}

export function middlewareImportName(
  middleware: CodegenMiddleware,
  routesDir: string,
): string {
  return stableImportName("middleware", routesDir, middleware.filePath);
}

function stableImportName(prefix: string, routesDir: string, filePath: string): string {
  const relativePath = normalizeImportKey(path.relative(routesDir, filePath));
  const readableName =
    prefix === "middleware"
      ? middlewareIdentifierPath(relativePath)
      : routeIdentifierPath(relativePath);
  return `${prefix}_${readableName}`;
}

function normalizeImportKey(relativePath: string): string {
  return relativePath.split(path.sep).join("/");
}

function routeIdentifierPath(relativePath: string): string {
  return encodeIdentifierSegments(relativePath.replace(/\.route\.tsx?$/, ""));
}

function middlewareIdentifierPath(relativePath: string): string {
  const directory = path.posix.dirname(relativePath);
  if (directory === ".") return "root";
  return encodeIdentifierSegments(directory);
}

function encodeIdentifierSegments(value: string): string {
  return value
    .split("/")
    .filter(Boolean)
    .map(encodeIdentifierSegment)
    .join("_") || "root";
}

function encodeIdentifierSegment(segment: string): string {
  if (segment.startsWith("$$")) {
    return `catchAll_${encodeIdentifierChars(segment.slice(2))}`;
  }
  if (segment.startsWith("$")) {
    return `param_${encodeIdentifierChars(segment.slice(1))}`;
  }
  if (segment.startsWith("_")) {
    return `group_${encodeIdentifierChars(segment.slice(1))}`;
  }
  return encodeIdentifierChars(segment);
}

function encodeIdentifierChars(value: string): string {
  let output = "";
  for (let index = 0; index < value.length; index += 1) {
    const char = value[index]!;
    if (/[A-Za-z0-9]/.test(char)) {
      output += char;
      continue;
    }

    switch (char) {
      case ".":
        output += "_";
        break;
      case "-":
        output += "_dash_";
        break;
      case "_":
        output += "_us_";
        break;
      default:
        output += `_u${char.codePointAt(0)!.toString(16)}_`;
        break;
    }
  }
  return output.replace(/^_+|_+$/g, "") || "root";
}

export function generateManifestSource(
  routes: CodegenRoute[],
  middlewares: CodegenMiddleware[],
  outFile: string,
  routesDir: string,
  extraImports: string[] = [],
): string {
  const outDir = path.dirname(outFile);
  const lines: string[] = [];

  lines.push("// ⚠️ Auto-generated by routed. Do not edit.");
  lines.push('import { defineRouteTree } from "routedjs";');

  for (const extraImport of extraImports) {
    lines.push(extraImport);
  }

  if (extraImports.length > 0) {
    lines.push("");
  }

  const middlewareImportNames: Map<string, string> = new Map();
  middlewares.forEach((mw) => {
    const importName = middlewareImportName(mw, routesDir);
    middlewareImportNames.set(mw.filePath, importName);
    lines.push(`import ${importName} from "${toRelativeImport(outDir, mw.filePath)}";`);
  });

  if (middlewares.length > 0) {
    lines.push("");
  }

  const routeImportNames: Map<string, string> = new Map();
  routes.forEach((route) => {
    const importName = routeImportName(route, routesDir);
    routeImportNames.set(route.filePath, importName);
    lines.push(`import ${importName} from "${toRelativeImport(outDir, route.filePath)}";`);
  });

  lines.push("");
  lines.push("export const routeTree = defineRouteTree([");

  for (const route of routes) {
    const routeName = routeImportNames.get(route.filePath)!;
    const routeRelativeDir = path.relative(routesDir, path.dirname(route.filePath));
    const applicableMiddleware = resolveMiddlewareForRoute(
      routeRelativeDir || ".",
      middlewares,
    );

    const middlewareArray = applicableMiddleware
      .map((mw) => middlewareImportNames.get(mw.filePath)!)
      .join(", ");

    lines.push("  {");
    lines.push(`    path: "${route.urlPath}",`);
    lines.push(`    method: "${route.method}",`);
    lines.push(`    route: ${routeName},`);
    lines.push(`    middleware: [${middlewareArray}],`);
    lines.push("  },");
  }

  lines.push("]);");
  lines.push("");

  return lines.join("\n");
}
