import path from "node:path";

export type CodegenRoute = {
  filePath: string;
  urlPath: string;
  method: string;
};

export type CodegenMiddleware = {
  filePath: string;
  directory: string;
};

export function resolveMiddlewareForRoute(
  routeRelativeDir: string,
  middlewares: CodegenMiddleware[],
): CodegenMiddleware[] {
  return middlewares.filter((mw) => {
    if (mw.directory === ".") return true;
    return (
      routeRelativeDir === mw.directory ||
      routeRelativeDir.startsWith(mw.directory + path.sep)
    );
  });
}

export function toRelativeImport(fromDir: string, toFile: string): string {
  let rel = path.relative(fromDir, toFile);
  if (!rel.startsWith(".")) {
    rel = "./" + rel;
  }
  return rel;
}

export function generateManifestSource(
  routes: CodegenRoute[],
  middlewares: CodegenMiddleware[],
  outFile: string,
  routesDir: string,
  extraImports: string[] = [],
): string {
  const outDir = path.dirname(outFile);
  const lines: string[] = [];

  lines.push("// ⚠️ Auto-generated by routed. Do not edit.");
  lines.push('import { defineRouteTree } from "routedjs";');

  for (const extraImport of extraImports) {
    lines.push(extraImport);
  }

  if (extraImports.length > 0) {
    lines.push("");
  }

  const middlewareImportNames: Map<string, string> = new Map();
  middlewares.forEach((mw, i) => {
    const importName = `middleware${i}`;
    middlewareImportNames.set(mw.filePath, importName);
    lines.push(`import ${importName} from "${toRelativeImport(outDir, mw.filePath)}";`);
  });

  if (middlewares.length > 0) {
    lines.push("");
  }

  const routeImportNames: Map<string, string> = new Map();
  routes.forEach((route, i) => {
    const importName = `route${i}`;
    routeImportNames.set(route.filePath, importName);
    lines.push(`import ${importName} from "${toRelativeImport(outDir, route.filePath)}";`);
  });

  lines.push("");
  lines.push("export const routeTree = defineRouteTree([");

  for (const route of routes) {
    const routeName = routeImportNames.get(route.filePath)!;
    const routeRelativeDir = path.relative(routesDir, path.dirname(route.filePath));
    const applicableMiddleware = resolveMiddlewareForRoute(
      routeRelativeDir || ".",
      middlewares,
    );

    const middlewareArray = applicableMiddleware
      .map((mw) => middlewareImportNames.get(mw.filePath)!)
      .join(", ");

    lines.push("  {");
    lines.push(`    path: "${route.urlPath}",`);
    lines.push(`    method: "${route.method}",`);
    lines.push(`    route: ${routeName},`);
    lines.push(`    middleware: [${middlewareArray}],`);
    lines.push("  },");
  }

  lines.push("]);");
  lines.push("");

  return lines.join("\n");
}
