// ⚠️ Auto-generated by routed. Do not edit.
import Koa from "koa";
import { routeHandler, wrapMiddleware } from "routedjs/koa";

import middleware0 from "./routes/_middleware.ts";
import middleware1 from "./routes/users/_middleware.ts";

import route0 from "./routes/health.get.route.ts";
import route1 from "./routes/_internal/metrics.get.route.ts";
import route2 from "./routes/users/index.get.route.ts";
import route3 from "./routes/users/index.post.route.ts";
import route4 from "./routes/users/$userId.delete.route.ts";
import route5 from "./routes/users/$userId.get.route.ts";
import route6 from "./routes/users/$userId.put.route.ts";
import route7 from "./routes/users/$userId/visits.get.route.ts";
import route8 from "./routes/users/$userId/visits/$visitId.get.route.ts";

export const app = new Koa();

app.use(wrapMiddleware(middleware0));
app.use(wrapMiddleware(middleware1));
app.use(routeHandler(route0, "/health", "get"));
app.use(routeHandler(route1, "/metrics", "get"));
app.use(routeHandler(route2, "/users", "get"));
app.use(routeHandler(route3, "/users", "post"));
app.use(routeHandler(route4, "/users/:userId", "delete"));
app.use(routeHandler(route5, "/users/:userId", "get"));
app.use(routeHandler(route6, "/users/:userId", "put"));
app.use(routeHandler(route7, "/users/:userId/visits", "get"));
app.use(routeHandler(route8, "/users/:userId/visits/:visitId", "get"));
