// ⚠️ Auto-generated by routed. Do not edit.
import { defineRouteTree } from "routedjs";
import Koa from "koa";
import { routeHandler, wrapMiddleware } from "routedjs/koa";

import middleware0 from "./routes/_middleware.ts";
import middleware1 from "./routes/users/_middleware.ts";

import route0 from "./routes/_internal/metrics.get.route.ts";
import route1 from "./routes/health.get.route.ts";
import route2 from "./routes/users/$userId/visits/$visitId.get.route.ts";
import route3 from "./routes/users/$userId/visits.get.route.ts";
import route4 from "./routes/users/$userId.delete.route.ts";
import route5 from "./routes/users/$userId.get.route.ts";
import route6 from "./routes/users/$userId.put.route.ts";
import route7 from "./routes/users/index.get.route.ts";
import route8 from "./routes/users/index.post.route.ts";

export const routeTree = defineRouteTree([
  {
    path: "/metrics",
    method: "get",
    route: route0,
    middleware: [middleware0],
  },
  {
    path: "/health",
    method: "get",
    route: route1,
    middleware: [middleware0],
  },
  {
    path: "/users/:userId/visits/:visitId",
    method: "get",
    route: route2,
    middleware: [middleware0, middleware1],
  },
  {
    path: "/users/:userId/visits",
    method: "get",
    route: route3,
    middleware: [middleware0, middleware1],
  },
  {
    path: "/users/:userId",
    method: "delete",
    route: route4,
    middleware: [middleware0, middleware1],
  },
  {
    path: "/users/:userId",
    method: "get",
    route: route5,
    middleware: [middleware0, middleware1],
  },
  {
    path: "/users/:userId",
    method: "put",
    route: route6,
    middleware: [middleware0, middleware1],
  },
  {
    path: "/users",
    method: "get",
    route: route7,
    middleware: [middleware0, middleware1],
  },
  {
    path: "/users",
    method: "post",
    route: route8,
    middleware: [middleware0, middleware1],
  },
]);

export const app = new Koa();

app.use(wrapMiddleware(middleware0));
app.use(wrapMiddleware(middleware1));
app.use(routeHandler(route0, "/metrics", "get"));
app.use(routeHandler(route1, "/health", "get"));
app.use(routeHandler(route2, "/users/:userId/visits/:visitId", "get"));
app.use(routeHandler(route3, "/users/:userId/visits", "get"));
app.use(routeHandler(route4, "/users/:userId", "delete"));
app.use(routeHandler(route5, "/users/:userId", "get"));
app.use(routeHandler(route6, "/users/:userId", "put"));
app.use(routeHandler(route7, "/users", "get"));
app.use(routeHandler(route8, "/users", "post"));
