// ⚠️ Auto-generated by routed. Do not edit.
import { defineRouteTree } from "routedjs";
import Koa from "koa";
import { routeHandler, wrapMiddleware } from "routedjs/koa";

import middlewareRoot from "./routes/_middleware.ts";
import middlewareUsers from "./routes/users/_middleware.ts";

import routeMetricsGet from "./routes/_internal/metrics.get.route.ts";
import routeHealthGet from "./routes/health.get.route.ts";
import routeUsersParamUserIdVisitsParamVisitIdGet from "./routes/users/$userId/visits/$visitId.get.route.ts";
import routeUsersParamUserIdVisitsGet from "./routes/users/$userId/visits.get.route.ts";
import routeUsersParamUserIdDelete from "./routes/users/$userId.delete.route.ts";
import routeUsersParamUserIdGet from "./routes/users/$userId.get.route.ts";
import routeUsersParamUserIdPut from "./routes/users/$userId.put.route.ts";
import routeUsersGet from "./routes/users/index.get.route.ts";
import routeUsersPost from "./routes/users/index.post.route.ts";

export const routeTree = defineRouteTree([
  {
    path: "/metrics",
    method: "get",
    route: routeMetricsGet,
    middleware: [middlewareRoot],
  },
  {
    path: "/health",
    method: "get",
    route: routeHealthGet,
    middleware: [middlewareRoot],
  },
  {
    path: "/users/:userId/visits/:visitId",
    method: "get",
    route: routeUsersParamUserIdVisitsParamVisitIdGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId/visits",
    method: "get",
    route: routeUsersParamUserIdVisitsGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId",
    method: "delete",
    route: routeUsersParamUserIdDelete,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId",
    method: "get",
    route: routeUsersParamUserIdGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId",
    method: "put",
    route: routeUsersParamUserIdPut,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users",
    method: "get",
    route: routeUsersGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users",
    method: "post",
    route: routeUsersPost,
    middleware: [middlewareRoot, middlewareUsers],
  },
]);

export const app = new Koa();

app.use(wrapMiddleware(middlewareRoot));
app.use(wrapMiddleware(middlewareUsers));
app.use(routeHandler(routeMetricsGet, "/metrics", "get"));
app.use(routeHandler(routeHealthGet, "/health", "get"));
app.use(routeHandler(routeUsersParamUserIdVisitsParamVisitIdGet, "/users/:userId/visits/:visitId", "get"));
app.use(routeHandler(routeUsersParamUserIdVisitsGet, "/users/:userId/visits", "get"));
app.use(routeHandler(routeUsersParamUserIdDelete, "/users/:userId", "delete"));
app.use(routeHandler(routeUsersParamUserIdGet, "/users/:userId", "get"));
app.use(routeHandler(routeUsersParamUserIdPut, "/users/:userId", "put"));
app.use(routeHandler(routeUsersGet, "/users", "get"));
app.use(routeHandler(routeUsersPost, "/users", "post"));
