// ⚠️ Auto-generated by routed. Do not edit.
import Elysia from "elysia";
import { routeHandler } from "routedjs/elysia";

import middleware0 from "./routes/_middleware.ts";
import middleware1 from "./routes/users/_middleware.ts";

import route0 from "./routes/health.get.route.ts";
import route1 from "./routes/_internal/metrics.get.route.ts";
import route2 from "./routes/users/index.get.route.ts";
import route3 from "./routes/users/index.post.route.ts";
import route4 from "./routes/users/$userId.delete.route.ts";
import route5 from "./routes/users/$userId.get.route.ts";
import route6 from "./routes/users/$userId.put.route.ts";
import route7 from "./routes/users/$userId/visits.get.route.ts";
import route8 from "./routes/users/$userId/visits/$visitId.get.route.ts";

export const app = new Elysia()
  .get("/health", routeHandler(route0, "/health") as any)
  .get("/metrics", routeHandler(route1, "/metrics") as any)
  .get("/users", routeHandler(route2, "/users") as any)
  .post("/users", routeHandler(route3, "/users") as any)
  .delete("/users/:userId", routeHandler(route4, "/users/:userId") as any)
  .get("/users/:userId", routeHandler(route5, "/users/:userId") as any)
  .put("/users/:userId", routeHandler(route6, "/users/:userId") as any)
  .get("/users/:userId/visits", routeHandler(route7, "/users/:userId/visits") as any)
  .get("/users/:userId/visits/:visitId", routeHandler(route8, "/users/:userId/visits/:visitId") as any)
;

export type AppType = typeof app;
