import path from "node:path";
import { createRouteImportNameMap } from "../codegen/manifest.ts";
import type { HttpMethod } from "../core/types.ts";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type ScannedRouteForClient = {
  filePath: string;
  urlPath: string;
  method: HttpMethod;
};

type GenerateClientOptions = {
  routes: ScannedRouteForClient[];
  outFile: string;
  routesDir: string;
};

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

export function generateClientCode(options: GenerateClientOptions): string {
  const { routes, outFile, routesDir } = options;
  const outDir = path.dirname(outFile);
  const routeImportNames = createRouteImportNameMap(routes, routesDir);
  const lines: string[] = [];

  lines.push("// ⚠️ Auto-generated by routed. Do not edit.");
  lines.push('import type { StandardSchemaV1 } from "@standard-schema/spec";');
  lines.push('import { createClient, type RouteMap, type Client, type ClientOptions } from "routedjs/client";');
  lines.push("");

  // Import each route file to extract its schema types
  routes.forEach((route) => {
    const importPath = toRelativeImport(outDir, route.filePath);
    lines.push(`import type ${routeImportNames.get(route.filePath)!} from "${importPath}";`);
  });

  lines.push("");

  // Helper type to extract schemas from a route definition
  lines.push("// Extract schema types from route definitions");
  lines.push("type InferSchema<T> = T extends { schemas: infer S } ? S : {};");
  lines.push("type SchemaType<T> = T extends StandardSchemaV1 ? StandardSchemaV1.InferOutput<T> : undefined;");
  lines.push("type PrimarySuccessResponse<T> =");
  lines.push("  T extends { 200: infer R } ? R :");
  lines.push('  T extends { "200": infer R } ? R :');
  lines.push("  T extends { 201: infer R } ? R :");
  lines.push('  T extends { "201": infer R } ? R :');
  lines.push("  T extends { 202: infer R } ? R :");
  lines.push('  T extends { "202": infer R } ? R :');
  lines.push("  T extends { 204: infer R } ? R :");
  lines.push('  T extends { "204": infer R } ? R :');
  lines.push("  undefined;");
  lines.push("");

  // Generate the RouteMap type
  lines.push("export type AppRouteMap = {");

  for (let i = 0; i < routes.length; i++) {
    const route = routes[i]!;
    const routeType = `typeof ${routeImportNames.get(route.filePath)!}`;
    const schemas = `InferSchema<${routeType}>`;

    lines.push(`  "${route.method} ${route.urlPath}": {`);
    lines.push(`    params: SchemaType<${schemas} extends { params: infer P } ? P : undefined>;`);
    lines.push(`    query: SchemaType<${schemas} extends { query: infer Q } ? Q : undefined>;`);
    lines.push(`    body: SchemaType<${schemas} extends { body: infer B } ? B : undefined>;`);
    lines.push(`    response: SchemaType<${schemas} extends { responses: infer R } ? PrimarySuccessResponse<R> : ${schemas} extends { response: infer R } ? R : undefined>;`);
    lines.push("  };");
  }

  lines.push("};");
  lines.push("");

  // Export a factory
  lines.push("export function createApiClient(options: ClientOptions): Client<AppRouteMap> {");
  lines.push("  return createClient<AppRouteMap>(options);");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function toRelativeImport(fromDir: string, toFile: string): string {
  let rel = path.relative(fromDir, toFile);
  if (!rel.startsWith(".")) {
    rel = "./" + rel;
  }
  return rel;
}
