import { describe, expect, test } from "bun:test";
import { generateClientCode } from "./codegen.ts";

describe("generateClientCode", () => {
  test("generates correct imports and route map", () => {
    const code = generateClientCode({
      routes: [
        { filePath: "/app/routes/health.get.route.ts", urlPath: "/health", method: "get" },
        { filePath: "/app/routes/users/index.get.route.ts", urlPath: "/users", method: "get" },
        { filePath: "/app/routes/users/index.post.route.ts", urlPath: "/users", method: "post" },
        { filePath: "/app/routes/users/$userId.get.route.ts", urlPath: "/users/:userId", method: "get" },
      ],
      outFile: "/app/routed.client.ts",
      routesDir: "/app/routes",
    });

    // Has auto-generated header
    expect(code).toContain("Auto-generated by routed");

    // Imports Standard Schema types (not Zod)
    expect(code).toContain('@standard-schema/spec');
    expect(code).not.toContain('import type { z }');

    // Imports from routed/client
    expect(code).toContain('import { createClient, type RouteMap, type Client, type ClientOptions } from "routedjs/client"');

    // Imports route types
    expect(code).toContain("import type route0 from");
    expect(code).toContain("import type route1 from");
    expect(code).toContain("import type route2 from");
    expect(code).toContain("import type route3 from");

    // Generates route map entries
    expect(code).toContain('"get /health"');
    expect(code).toContain('"get /users"');
    expect(code).toContain('"post /users"');
    expect(code).toContain('"get /users/:userId"');

    // Exports createApiClient factory
    expect(code).toContain("export function createApiClient");
    expect(code).toContain("createClient<AppRouteMap>");
  });

  test("generates correct relative imports", () => {
    const code = generateClientCode({
      routes: [
        { filePath: "/project/src/routes/health.get.route.ts", urlPath: "/health", method: "get" },
      ],
      outFile: "/project/src/routed.client.ts",
      routesDir: "/project/src/routes",
    });

    // Import should be relative from outFile to route file
    expect(code).toContain("./routes/health.get.route.ts");
  });

  test("empty routes produces valid code", () => {
    const code = generateClientCode({
      routes: [],
      outFile: "/app/client.ts",
      routesDir: "/app/routes",
    });

    expect(code).toContain("export type AppRouteMap = {");
    expect(code).toContain("};");
    expect(code).toContain("export function createApiClient");
  });
});
