// ⚠️ Auto-generated by routed. Do not edit.
import { defineRouteTree } from "routedjs";
import { Hono } from "hono";
import { routeHandler, wrapMiddleware } from "routedjs/hono";

import middlewareRoot from "./routes/_middleware.ts";
import middlewareUsers from "./routes/users/_middleware.ts";

import routeMetricsGet from "./routes/_internal/metrics.get.route.ts";
import routeHealthGet from "./routes/health.get.route.ts";
import routeUsersParamUserIdVisitsParamVisitIdGet from "./routes/users/$userId/visits/$visitId.get.route.ts";
import routeUsersParamUserIdVisitsGet from "./routes/users/$userId/visits.get.route.ts";
import routeUsersParamUserIdDelete from "./routes/users/$userId.delete.route.ts";
import routeUsersParamUserIdGet from "./routes/users/$userId.get.route.ts";
import routeUsersParamUserIdPut from "./routes/users/$userId.put.route.ts";
import routeUsersGet from "./routes/users/index.get.route.ts";
import routeUsersPost from "./routes/users/index.post.route.ts";
import routeMeGet from "./routes/me/index.get.route.ts";

export const routeTree = defineRouteTree([
  {
    path: "/metrics",
    method: "get",
    route: routeMetricsGet,
    middleware: [middlewareRoot],
  },
  {
    path: "/health",
    method: "get",
    route: routeHealthGet,
    middleware: [middlewareRoot],
  },
  {
    path: "/users/:userId/visits/:visitId",
    method: "get",
    route: routeUsersParamUserIdVisitsParamVisitIdGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId/visits",
    method: "get",
    route: routeUsersParamUserIdVisitsGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId",
    method: "delete",
    route: routeUsersParamUserIdDelete,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId",
    method: "get",
    route: routeUsersParamUserIdGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users/:userId",
    method: "put",
    route: routeUsersParamUserIdPut,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users",
    method: "get",
    route: routeUsersGet,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/users",
    method: "post",
    route: routeUsersPost,
    middleware: [middlewareRoot, middlewareUsers],
  },
  {
    path: "/me",
    method: "get",
    route: routeMeGet,
    middleware: [middlewareRoot],
  },
]);

export const app = new Hono()
  .use("*", wrapMiddleware(middlewareRoot))
  .use("/users/*", wrapMiddleware(middlewareUsers))
  .get("/metrics", routeHandler(routeMetricsGet, "/metrics"))
  .get("/health", routeHandler(routeHealthGet, "/health"))
  .get("/users/:userId/visits/:visitId", routeHandler(routeUsersParamUserIdVisitsParamVisitIdGet, "/users/:userId/visits/:visitId"))
  .get("/users/:userId/visits", routeHandler(routeUsersParamUserIdVisitsGet, "/users/:userId/visits"))
  .delete("/users/:userId", routeHandler(routeUsersParamUserIdDelete, "/users/:userId"))
  .get("/users/:userId", routeHandler(routeUsersParamUserIdGet, "/users/:userId"))
  .put("/users/:userId", routeHandler(routeUsersParamUserIdPut, "/users/:userId"))
  .get("/users", routeHandler(routeUsersGet, "/users"))
  .post("/users", routeHandler(routeUsersPost, "/users"))
  .get("/me", routeHandler(routeMeGet, "/me"))
;

export type AppType = typeof app;
